title: "Reeshad Khan, Ph.D."
description: "Computer vision and autonomous systems researcher focused on efficient 3D perception, BEV-based autonomous perception and planning, multisensor fusion, and robust learning under noisy and resource-constrained sensing conditions. "
url: "https://reeshad-khan.github.io"
markdown: kramdown
plugins: []

mapmyvisitors_id: mmOAOnOgy6tTB8zJmgwURWLzE3wb7o_o8-qFa0Ymtgk
flagcounter_id: KIl
pulsemaps_map_url: ""
